apiVersion: v1
kind: Service
metadata:
  name: ai-studyplan-backend-service
spec:
  type: LoadBalancer   # Exposes the service to the internet
  selector:
    app: ai-studyplan-backend
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 80  # Container port
